#!/bin/sh

set -e

# Defaults
REPO=/backup/$(hostname)

test -e /etc/borgme.conf && . /etc/borgme.conf
test -e /usr/local/etc/borgme.conf && . /etc/borgme.conf
test -e ~/.borgme.conf && . ~/.borgme.conf

# Force the following to always be exclude in a system backup
SYSTEM_EXCLUDE=(/proc /sys /tmp /dev ${SYSTEM_EXCLUDE[@]})
VERBOSE="-s --progress"

borg_user() {
	user=${1}

	# Get home directory to backup
	user_home="/home/${user}"
	user_home_var="${user}_HOME"
	if [ -n "${!user_home_var}" ]; then
		user_home="${!user_home_var}"
	fi

	# Setup exclude flags
	user_exclude_var="${user}_EXCLUDE[@]"
	exclude_flags=""
	for ex in ${!user_exclude_var}; do
		# Each exclude is relative to the home dir
		exclude_flags="${exclude_flags} --exclude ${user_home}/${ex}"
	done
	
	borg create \
		 ${VERBOSE} \
		 --exclude-cache \
		 ${exclude_flags} \
		 "${REPO}::user-${user}-{now}" ${user_home}
}

borg_users() {
	for user in ${USERS[*]}; do
		borg_user ${user}
	done
}

borg_system() {
	# Setup exclude flags
	exclude_flags=""
	for ex in ${SYSTEM_EXCLUDE[@]}; do
		exclude_flags="${exclude_flags} --exclude ${ex}"
	done

	borg create \
		 ${VERBOSE} \
		 --exclude-cache \
		 ${exclude_flags} \
		 "${REPO}::system-{now}" /
}

list_users() {
	for user in ${USERS[@]}; do
		echo ${user}
	done
}

help() {
	echo "Usage: ${0} [flags] [command]"
	echo
	echo "Commands:"
	echo "  user   [username]  Backup the user with given username"
	echo "  users              Backup all users"
	echo "  system             Backup the entire system"
	echo "  list               List users configured to be backed up"
	echo "  help               This"
	echo
	echo "Flags:"
	echo "  -q        Quiet mode"
	echo
	echo "Example"
	echo "  ${0} -q user foobar"
}

flags="${1}"
if [ "${flags:0:1}" = "-" ]; then
	flags=${flags#'-'}
	while [ -n "${flags}" ]; do
		  f=${flags:0:1}
		  case ${f} in
			  "q")
				  VERBOSE=""
				  ;;
		  esac
		  flags=${flags:1}
	done
	shift
fi

arg=${1}
opt=${2}
case ${arg} in
	"user")
		borg_user ${opt}
		;;
	"users")
		borg_users
		;;
	"system")
		borg_system
		;;
	"list")
		list_users
		;;
	*)
		help
		;;
esac

exit 0
